#!/bin/bash
# liuliqiao
# 2015-11-30

[[ -d /svndata/games || -d /svndata/services ]] || { echo 1; exit; }

if [[ "$1" = "bak" ]]; then	#回滚方式备份
    time=$(date +%y%m%d-%H%M%S)
    [ -d /data/Go_back ] || mkdir -p /data/Go_back
    rsync --port 1888 --bwlimit=20000 --delete --exclude=.svn --exclude=log/ --exclude=core -avz /svndata/ /data/Go_back/svndata.${time}.ver
    if [ $(ls -Al /data/Go_back|wc -l) -gt 6 ];then
        line=$(ls /data/Go_back|sort -n|head -1)
        rm -rf /data/Go_back/$line
    fi

elif [[ "$1" = "check" ]]; then	#检查备份是否成功
    cd /data/Go_back
    time=$(date +%y%m%d)
    newsize=$(du -sb svndata.${time}* |awk '{print $1}')
    oldtime=$(date -d '-1 day' +%y%m%d)
    oldsize=$(du -sb svndata.${oldtime}* |awk '{print $1}')
    size=$((${newsize}-${oldsize}))

    if [ $size -ge -20000000  -a  $size -le 20000000 ]; then
        echo 1
    else
        echo 0
    fi
fi
