#!/bin/bash
# 1un
# 2015-10-26
# mongo数据库按天备份,注意修改库名

OldDate=$(date -d '-1 day' +%F)
NowDate=$(date +%F)
DBNAME=ddz_$OldDate
BakName=mongo-${DBNAME}
Tpath=/alidata1/tmp
KeepName=mongo-ddz_$(date -d '-6 day' +%F)

#按照端口循环备份mongo
for port in $(netstat -tlnp|grep -v ^tcp6|grep mongo|awk -F: '{print $2}'|awk '{print $1}')
do
    Bpath=/data/mongod_backup/$port

    [[ ! -d $Bpath ]] && mkdir -p $Bpath
    [[ ! -d $Tpath ]] && mkdir -p $Tpath
    
    /usr/bin/mongodump --port $port -d $DBNAME -o $Tpath &> /dev/null
    
    cd $Tpath
    tar acf $Bpath/${BakName}.tgz $DBNAME
    
    if [ "$?" == "0" ]; then
        echo "$NowDate ${HOSTNAME} filename:${BakName}.tgz size+$(du -sb $Bpath/$BakName.tgz|cut -f1)+ backup success!" >> ${Bpath}/mongod.log
        md5sum $Bpath/$BakName.tgz >> $Bpath/md5sum.log
    else
        echo "$NowDate ${HOSTNAME} mongodb backup +failed+" >> ${Bpath}/mongod.log
    fi
    
    rm -rf $Tpath/$DBNAME
    rm -rf $Bpath/$KeepName.tgz
done

