#!/bin/bash
# 1un
# 2015-10-28
# 获取tcp状态,出图展示

Help(){
cat << EOF

  Usage: $0 { ESTABLISHED | SYN_SENT | SYN_RECV | FIN_WAIT1 | FIN_WAIT2 | TIME_WAIT | CLOSE_WAIT | LAST_ACK | LISTEN | CLOSING }

    ESTABLISHED	= 代表一个打开的连接
    SYN_SENT	= 再发送连接请求后等待匹配的连接请求
    SYN_RECV	= 再收到和发送一个连接请求后等待对方对连接请求的确认
    FIN_WAIT1	= 等待远程TCP连接中断请求，或先前的连接中断请求的确认
    FIN_WAIT2	= 从远程TCP等待连接中断请求
    TIME_WAIT	= 等待足够的时间以确保远程TCP接收到连接中断请求的确认
    CLOSED	= 没有任何连接状态
    CLOSE_WAIT	= 等待从本地用户发来的连接中断请求
    LAST_ACK	= 等待原来的发向远程TCP的连接中断请求的确认
    LISTEN	= 侦听来自远方的TCP端口的连接请求
    CLOSING	= 等待远程TCP对连接中断的确认

EOF
exit
}

[[ $# -lt 1 || $1 = "help" ]] && Help

num=$(netstat -na | awk '/^tcp/ {++S[$NF]} END {for(a in S) print a, S[a]}' | grep "$1"|awk '{print $2}')
echo ${num:=0}

