#!/bin/bash
# 1un
# 2015-10-26
# 检查防火墙是否开启

A=10.0.0.0
B=`/sbin/iptables-save|egrep -o "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}"|grep "10.0.0.0"`
if [[ $A = $B ]]
then 
	echo 1
else
	echo 0 
fi
